# Generated by Django 4.2.10 on 2025-02-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_location_users_address_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='address_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='address_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='address_street',
            new_name='street',
        ),
    ]
