# Generated by Django 4.2.10 on 2025-02-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_profile_created_at_remove_users_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
