# Generated by Django 4.2.10 on 2025-02-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileimg',
            new_name='profile_image',
        ),
    ]
