# Generated by Django 4.2.10 on 2025-02-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_groupmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='nickname',
            new_name='group_name',
        ),
    ]
