# Generated by Django 4.2.10 on 2025-02-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_groupcontact_delete_groupmember_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcontact',
            old_name='group_name',
            new_name='contact_name',
        ),
    ]
